services:
  dev-server:
    image: squidfunk/mkdocs-material:9
    ports:
      - 8000:8000
    volumes:
      - .:/docs:ro
    command:
      - serve
      - --dev-addr=0.0.0.0:8000
      - --watch=.

